# Generated by Django 3.2.6 on 2021-09-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(max_length=12)),
                ('sirname', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('displayname', models.CharField(max_length=30)),
                ('customer_email', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField(max_length=6)),
                ('mobilenumber', models.IntegerField(max_length=10)),
                ('customerwebsite', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=12)),
                ('prod_unit', models.IntegerField(max_length=10)),
                ('prod_selling_price', models.IntegerField(max_length=10)),
                ('prod_desc', models.CharField(max_length=12)),
            ],
        ),
    ]
