# Generated by Django 3.2.6 on 2021-09-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_selling_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_unit',
            field=models.IntegerField(),
        ),
    ]
