# Generated by Django 3.2.6 on 2021-09-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210903_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='companyname',
            field=models.CharField(default='Google', max_length=30),
        ),
    ]
