# Generated by Django 3.2.6 on 2021-09-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_customer_companyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prod_selling_price',
            new_name='number_of_product',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='prod_desc',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='prod_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='prod_unit',
            new_name='selling_price',
        ),
    ]
